modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"


[[mods]]
    modId="upgradedechests"
    version="1.0.3-1.19.4"
    displayName="Upgraded Ender Chests"
    logoFile="pack.png"
    authors="kyrptonaught"
    description="More Ender Chests!"
    itemIcon="upgradedechests:rift_ender_chest"
    configBackground="minecraft:textures/block/end_stone_bricks.png" # But no config here, pretty cool huh?

[[dependencies.upgradedechests]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.upgradedechests]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"